spring.application.name=scm
server.port=8081

# mysql database configurations
#                  protocol : DB : server  : port no : schema(DB name)
spring.datasource.url=jdbc:mysql://localhost:3306/SCM_Project
spring.datasource.username=root
spring.datasource.password=Swap25

# jpa configurations
spring.jpa.show-sql=true
# for creating tables if not exist
spring.jpa.hibernate.ddl-auto=create
# dialect which is optional cause we have added it's jar and dependency.
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect


# email configurations
